# Site settings
title: A way to Data Scientist
email: anyinlover@gmail.com
description: >
 Find a way to become a data scientist by self-study.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anyinlover.github.io" # the base hostname & protocol for your site

author:
  fullname: anyinlover
  # googleplus: https://www.google.com/+MotaquillahMaddane
  github: anyinlover
  # twitter: electrik_frog
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown


